extra-deps:
  - ghcjs-dom-0.2.4.0
  - ref-tf-0.4.0.1
  - zenc-0.1.1
packages:
  - '.'
  - extra-dep: true
    location:
        git: git@github.com:/jonathanknowles/reflex
        commit: a63aba90bdea5ae5b3e1506d468613bdfedcdfa3
  - extra-dep: true
    location:
        git: git@github.com:/jonathanknowles/reflex-dom
        commit: fca15fd1b8a2dd34e53994553907f648091c7870


resolver: lts-6.25
compiler: ghcjs-0.2.0.9006025_ghc-7.10.3
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006025_ghc-7.10.3:
         url: http://ghcjs.tolysz.org/lts-6.25-9006025.tar.gz
         sha1: 3c87228579b55c05e227a7876682c2a7d4c9c007

