extra-deps:
  - ghcjs-dom-0.2.4.0
  - ref-tf-0.4.0.1
  - zenc-0.1.1
  - dependent-map-0.2.4.0
  - prim-uniq-0.1.0.1
  - containers-0.5.7.1


packages:
  - '.'
  - '../UI/reflex'
  - '../UI/ghcjs-dom'
  - '../UI/reflex-dom'
  - '../UI/ghcjs-base'
  - '../UI/ghcjs-prim'

resolver: lts-6.25
compiler: ghcjs-0.2.0.9006025_ghc-7.10.3
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006025_ghc-7.10.3:
         url: http://ghcjs.tolysz.org/lts-6.25-9006025.tar.gz
         sha1: 3c87228579b55c05e227a7876682c2a7d4c9c007

