resolver: lts-6.25
compiler: ghcjs-0.2.0.9006025_ghc-7.10.3
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006025_ghc-7.10.3:
         url: http://ghcjs.tolysz.org/lts-6.25-9006025.tar.gz
         sha1: 3c87228579b55c05e227a7876682c2a7d4c9c007

packages:
- location: .
- '../ghcjs-base'

- location:
    git: https://github.com/ryantrinkle/reflex.git
    commit: 5b5a1c8d540ea9058988d4c564e2823aa099b840
  extra-dep: true

- location:
    git: https://github.com/themoritz/reflex-dom.git
    commit: bb49bbf
  extra-dep: true

extra-deps:
- ghcjs-dom-0.2.3.1
- ref-tf-0.4
- aeson-0.10.0.0

require-stack-version: ">= 0.1.8"